IF NOT EXISTS( SELECT TOP 1 1 FROM sys.tables WHERE [name] = 'todo' )
BEGIN
	CREATE TABLE [todo] (
		[Id] INT IDENTITY(1,1) CONSTRAINT PK_todo PRIMARY KEY,
		[Title] NVARCHAR(MAX) NOT NULL,
		[IsDone] BIT NOT NULL
	)
END